name: Loom

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - 'asynchronix/src/runtime/executor/queue.rs'
      - 'asynchronix/src/runtime/executor/queue/**'
      - 'asynchronix/src/runtime/executor/task.rs'
      - 'asynchronix/src/runtime/executor/task/**'

jobs:
  loom:
    name: Loom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test (Loom)
        run: cargo test --tests --release
        env:
          RUSTFLAGS: --cfg asynchronix_loom